name: golang
version: 0.1
description: An example golang application with no database. For more information about using this template, including OpenShift considerations, see https://github.com/sclorg/nodejs-ex/blob/master/README.md.
keywords:
- quickstart
- golang
home: https://access.redhat.com
sources:
- https://github.com/3sky/golang-opc4
